### ISSUE TITLE
ConfigWatch ignores first value for a "context"

### ISSUE THREAD

**Issue by beeva-pablovaliente** [spring-cloud/spring-cloud-consul#288] opened 2017-03-08 16:53 UTC
Hello all!

Continuing the thread in: https://github.com/spring-cloud/spring-cloud-config/issues/635#issuecomment-285084901

We are experiencing some problems when trying to recover some properties for the first time from Consul.

My scenario is as follows:

* My application starts when consul is still empty
* After application is started, a key is written in consul (manually)
* The application cannot detect this first change until a new change is made again in consul. When the second change happens, the event that arise, contains both updated keys.

Is there any way to fix this? I was previously using the 1.0.2-RELEASE version of Spring Cloud Consul Config and this didn't happen.

Thanks!

**Comment by spencergibb** [comment] 2017-03-08 16:58
Is this a duplicate of #278

**Comment by beeva-pablovaliente** [comment] 2017-03-08 17:02
For sure is the same symptom  :)

**Closed** 2017-03-08 17:03 UTC
Labels: duplicate
