### ISSUE TITLE
Consul service ids must not be empty, must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen: null

### ISSUE THREAD

**Issue by ffroliva** [spring-cloud/spring-cloud-consul#747] opened 2021-08-24 15:26 UTC
Setup:
Java version: 14
Spring Clould 2020.0.3

I have create a simple application using spring initializer and tried to register it in Consul using docker.

I have the following in `bootstrap.yml`: 

```yaml
# ======================================================================
# SPRING CLOUD CONSUL CONFIGURATION
# ======================================================================
spring:
  application:
    name: "demo"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path:}/actuator/health
        health-check-interval: 15s
        health-check-timeout: 90s
        health-check-critical-timeout: 3m
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}
```

The application main method:

```java 
@EnableDiscoveryClient
@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}

@RestController
class DemoController{
	@GetMapping("/greeting/{name}")
	public ResponseEntity<String> greeting(@PathVariable String name) {
		return ResponseEntity.ok("Hello "+ name);
	}
}
```

I have a `docker-compose.yml` with consul configured.

```yaml
version: "3.7"
services:
  consul:
    image: consul:1.10.1
    container_name: consul
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0
    restart: unless-stopped
```

When I start the application I am getting the following error:

```java 
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.4.10)

2021-08-24 15:53:29.772  INFO 3996 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication using Java 14.0.2 on flavio1 with PID 3996 (C:\development\test\demo\target\classes started by ffrol in C:\development\test\demo)
2021-08-24 15:53:29.784  INFO 3996 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to default profiles: default
2021-08-24 15:53:42.823  INFO 3996 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=7a999276-c3f1-3a0d-8c84-cbb43801d6f3
2021-08-24 15:53:43.770  INFO 3996 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-08-24 15:53:43.790  INFO 3996 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-08-24 15:53:43.792  INFO 3996 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.52]
2021-08-24 15:53:44.493  INFO 3996 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-08-24 15:53:44.493  INFO 3996 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 14211 ms
2021-08-24 15:53:52.622  WARN 3996 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration': Unsatisfied dependency expressed through field 'autoServiceRegistration'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consulAutoServiceRegistration' defined in class path resource [org/springframework/cloud/consul/serviceregistry/ConsulAutoServiceRegistrationAutoConfiguration.class]: Unsatisfied dependency expressed through method 'consulAutoServiceRegistration' parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'consulRegistration' defined in class path resource [org/springframework/cloud/consul/serviceregistry/ConsulAutoServiceRegistrationAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.consul.serviceregistry.ConsulAutoRegistration]: Factory method 'consulRegistration' threw exception; nested exception is java.lang.IllegalArgumentException: Consul service ids must not be empty, must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen: null
...
```

My understanding is that `instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}` is correct.

What am I missing here? 

Sample code attached:
[demo.zip](https://github.com/spring-cloud/spring-cloud-consul/files/7040308/demo.zip)

Thank you in advance.

**Comment by murphye** [comment] 2022-05-06 04:39
I also ran into this. Not obvious what the problem is, and I reviewed the docs.

**Comment by StringKe** [comment] 2022-05-30 08:31
`spring.application.name` cannot use `@project.artifactId@` or `@artifactId@` to get the name.

**Comment by bilal89hayat** [comment] 2023-01-04 11:00
Error : **Caused by: java.lang.IllegalArgumentException: Consul service ids must not be empty, must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen: 8001**

Solution : 
spring.application.name= service_name

Consul Properties : 
  cloud:
    consul:
      discovery:
        enabled: true                          #Is service discovery enabled
        register: true                         #Register as a service in consul.
        deregister: 'false'                    #Disable automatic de-registration of service in consul.
        health-check-path: /project-management/actuator/health
        health-check-interval: 3s              #How often to perform the health check
        health-check-critical-timeout: 5s
        scheme: http
        health-check-tls-skip-verify: 'true'  #Skips certificate verification during service checks if true, otherwise runs certificate verification.
        prefer-ip-address: 'true'
        register-health-check: 'true'
      port: '8500'
      host: consul-headless

**Comment by spencergibb** [comment] 2023-03-08 22:26
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Closed by spencergibb** 2023-03-08 22:26 UTC
Labels: waiting-for-triage
