### ISSUE TITLE
IntegrationTest failing due to ServerProperties

### ISSUE THREAD

**Issue by hbxu** [spring-cloud/spring-cloud-consul#151] opened 2016-03-10 21:29 UTC
Hi,

I noticed that my build was broken after adding  
```
@SpringBootApplication
@EnableDiscoveryClient
public class Application 
...
```
The unit test looks like: 
```
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = { Application.class })
public class myTest
```

The jar is working.

This is the error that I am getting, when I enable my unittests:
-------------------
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consulDiscoveryClient' defined in class path resource [org/springframework/cloud/consul/discovery/ConsulDiscoveryClientConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [org.springframework.boot.autoconfigure.web.ServerProperties]: : No qualifying bean of type [org.springframework.boot.autoconfigure.web.ServerProperties] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.boot.autoconfigure.web.ServerProperties] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
```

**Comment by spencergibb** [comment] 2016-03-11 00:43
Duplicate of #149

**Closed by spencergibb** 2016-03-11 00:43 UTC
Labels: duplicate
