### ISSUE TITLE
Memory leak with Consul Config Watch

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-consul#183] opened 2016-05-10 14:39 UTC
I raised the following issue on Stackoverflow because I was experiencing my Spring Boot app just eating away at the heap

https://stackoverflow.com/questions/37137358/huge-org-springframework-boot-loader-launchedurlclassloader-memory-usage

After investigation is appears as though Consul is returning a changing `X-Consul-Index` header value when requesting KVs that do not exist.

For example `http://consul:8500/v1/kv/mio/application,server/?recurse&wait=2s&index=281722`, where `mio/application,server` is the default content and one of the active Spring profiles. 281722 was the index value returned from the previous call, and Consul may now return a completely different value.

A changing `X-Consul-Index` value causes the Spring Cloud to refresh the context (via `org.springframework.cloud.consul.config.ConfigWatch#watchConfigKeyValues`), which in turn creates a new instance of `org.springframework.cloud.consul.config.ConsulPropertySourceLocator`. For whatever reason, the old instance of ConsulPropertySourceLocator aren't garbage collected, leading to a memory leak.

I'm using Spring Boot c1.3.2.RELEASE, Spring Cloud vBrixton.RC2 and Consul v0.6.4.

At the moment the only way round this for us is disable config watch via `spring.cloud.consul.config.watch.enabled`

**Comment by dsyer** [comment] 2016-05-10 17:47
Can you debug your app and put a break point in the `ConsulPropertySourceLocator` constructor. Capture the stack when that is called (after startup), and attach it here. Or we could do that if you send us a simple sample to reproduce the issue. I don't see any calls to the constructor once my sample app is up and running.

**Comment by nickcodefresh** [comment] 2016-05-10 21:21
Yep sure, I'll do that tomorrow. It'll have to be the stack, as i don't have the time to create a sample app alas.

**Comment by dsyer** [comment] 2016-05-11 06:09
Actually, nevermind about the breakpoint: your analysis already points at the config watch as a problem (but our samples don't get pinged with that `X-Consul-Index` thing), and you can simulate the same thing just by POSTing to /refresh. What we need is to check your classpath for old versions of stuff, because we don't think there is a leak in the latest spring-cloud-context.

This issue looks like it belongs in spring-cloud-commons, but we can keep pushing on it here till we understand what's going on.

**Comment by nickcodefresh** [comment] 2016-05-11 07:10
I'm not sure how you want me to check the classpath, but here's the Maven dependency tree output
 
[output.txt](https://github.com/spring-cloud/spring-cloud-consul/files/258730/output.txt)

**Comment by dsyer** [comment] 2016-05-11 07:52
Thanks, that's useful, but rules out a classpath issue I think. Still it would be a good idea for you to try with the latest code (Brixton.RELEASE is all but done, so try a snapshot and tell us what happens).

**Comment by choppedpork** [comment] 2016-05-11 09:09
You should be able to reproduce a fairly quickly changing X-Consul-Index by using Consul as a docker overlay network backend - we've had it set up with a single (unused) overlay network and I think this is what was causing the constant index increase (since I've removed it the index hasn't changed for 12+ hrs).

**Comment by nickcodefresh** [comment] 2016-05-11 10:41
We tried using Spring Cloud Brixton.BUILD-SNAPSHOT but we had the same issue of an ever increasing classes loaded metric.

**Comment by dsyer** [comment] 2016-05-11 10:52
Did you try triggering a manual garbage collection? Is this with or without the `X-Consul-Index` forcing a refresh all the time?

**Comment by nissel** [comment] 2016-07-18 14:30
I noticed a similar memory leak, with lots of cglib enhanced MethodProxy classes but using the Eureka, every Eureka registry update / healthcheck created some more classes, one for each registered instance in Eureka.

I was going to raise an issue but the updating to the latest version of spring boot 1.3.6 fixed the problem for me. Not sure if it was 1.3.4 or 1.3.5 where I was seeing the issue.

**Comment by spencergibb** [comment] 2016-09-07 12:22
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by dahamr** [comment] 2016-09-08 14:53
We have run into something that may be similar. I've put together a simple service to reproduce.

https://github.com/dahamr/springCloudConsulTest

If I understand the additional information you are requesting:
- yes I forced a manual gc in visualvm before taking the heap dump
- I did not use the /refresh endpoint to reproduce

**Comment by spencergibb** [comment] 2016-09-08 15:01
@dahamr can you be more detailed about what you can "reproduce"? Do you see unbounded memory growth that never gets reclaimed?

**Comment by dahamr** [comment] 2016-09-08 16:22
Yes, I see memory growth that never gets reclaimed. For every refresh generated by the consul update, I see a new instance of AnnotationConfigApplicationContext being created and the old one is never reclaimed. It isn't a substantial amount of memory but we ultimately hit the "java.lang.OutOfMemoryError: GC overhead limit exceeded" exception.

**Comment by spencergibb** [comment] 2016-09-08 20:30
@dahamr I had to comment out your tests as they were written for boot 1.4.

Also, I changed the `build.gradle` to use the BOM rather than managing versions by hand (there were mismatched versions).

```gradle
dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Brixton.SR5'
    }
}

dependencies {
    compile "org.springframework.cloud:spring-cloud-starter-consul-all"
//    runtime "org.springframework.cloud:spring-cloud-consul-core:1.0.0.RELEASE"
//    runtime "org.springframework.cloud:spring-cloud-consul-config:1.0.2.RELEASE"
//    runtime "org.springframework.cloud:spring-cloud-consul-discovery:1.0.0.RELEASE"
//    runtime "org.springframework.cloud:spring-cloud-context:1.1.1.RELEASE"
//    compile "org.springframework.cloud:spring-cloud-commons:1.1.0.RELEASE"
//    runtime "com.ecwid.consul:consul-api:1.1.9"
//    runtime 'joda-time:joda-time:2.8.2'
    
    // dependencies stated in https://cloud.spring.io/spring-cloud-consul for consul retry
    compile 'org.springframework.retry:spring-retry'
    compile("org.springframework.boot:spring-boot-starter-aop")

    compile("org.springframework.boot:spring-boot-starter-web")
    // tag::actuator[]
    compile("org.springframework.boot:spring-boot-starter-actuator")
    // end::actuator[]
    // tag::tests[]
    testCompile("org.springframework.boot:spring-boot-starter-test")
    // end::tests[]
}
```

I only ever see one `AnnotationConfigApplicationContext`.

![applicationcontextcount](https://cloud.githubusercontent.com/assets/594085/18365512/faab0ba6-75e0-11e6-8bf2-068e8bd93fd6.png)


Going to let this run (updated property every second) for a while to see if I see a leak. If there is it doesn't match what you've reported.

**Comment by spencergibb** [comment] 2016-09-08 20:56
visual vm was borked, I'm seeing the increate in `AnnotationConfigApplicationContext` instances

**Comment by spencergibb** [comment] 2016-09-08 21:05
@dahamr what are your memory settings? how long until the OOM error? Each instance is just over 100b.

**Comment by dahamr** [comment] 2016-09-08 21:27
Agreed. Its pretty small even when you take into account what visualvm reports as the retained space. The services that failed first were basically running with about 30-40M free normally but would OOM in half a day with very little load. Turned out the reason the small memory leak turned into a problem was way too many unnecessary refresh events. I didn't really know how X-CONSUL-INDEX worked until this surfaced. We did not create service specific prefixes for every service. This caused those particular services to see every update to consul in any KV under the config prefix. These services also had the smallest heapsize so they ate dirt first.

We moved back to spring boot 1.3.5 for now but also plan to add a prefix for every service to prevent the unnecessary refreshes.

**Comment by spencergibb** [comment] 2016-09-08 21:33
Wait, moving to boot 1.3.5 fixes the issue?

**Comment by spencergibb** [comment] 2016-09-08 21:44
@dsyer @philwebb When I moved the sample above to boot 1.3.5 I get the familiar sawtooth heap graph. With boot 1.3.6 I see steady heap growth. What changed then that would cause the difference. With many refreshes we create new contexts with [`ContextRefresher`](https://github.com/spring-cloud/spring-cloud-commons/blob/v1.1.1.RELEASE/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java) (same version with boot 1.3.5 and 1.3.6.

**Comment by spencergibb** [comment] 2016-09-08 21:50
maybe I spoke too soon on 1.3.5, I'll let it run some more. It might be more the prefixes than anything since you wouldn't be sharing a hierarchy and only refreshing intermittently.

**Comment by philwebb** [comment] 2016-09-08 21:52
We [closed 61 issues](https://github.com/spring-projects/spring-boot/milestone/64?closed=1) in Spring Boot 1.3.6. At this point in the release cycle, there shouldn't be any major differences. Of course, we also updated the Spring Framework release so there's a possibility that something in core also aggravated the issue.

**Comment by spencergibb** [comment] 2016-09-08 21:52
@philwebb thanks for the note. I may have been hasty in my assessment of the 1.3.5 change.

**Comment by philwebb** [comment] 2016-09-08 21:53
OK, let me know if we need to do some `git bisect` magic!

**Comment by spencergibb** [comment] 2016-09-08 21:54
looks like our refresh leaks memory. refreshing often with consul and the shared key hierarchy just made the leak more obvious.

**Comment by spencergibb** [comment] 2016-09-09 17:23
boot 1.4 may solve the issue @philwebb @dsyer @dahamr 
![refreshspringboot140](https://cloud.githubusercontent.com/assets/594085/18396248/9df9c158-7690-11e6-9a31-9d7e79b069fa.png)

**Comment by spencergibb** [comment] 2016-09-09 18:24
As promised 1.3.6
![refreshspringboot136](https://cloud.githubusercontent.com/assets/594085/18398073/09b9af68-7699-11e6-9c05-ccf73ad14f8b.png)

**Comment by spencergibb** [comment] 2016-09-09 19:36
Another try of 1.4.0 😢 

![refreshspringboot140 round 2](https://cloud.githubusercontent.com/assets/594085/18400286/2bba2944-76a3-11e6-8b0b-4af64051dd20.png)

**Comment by dahamr** [comment] 2016-09-09 21:09
The testing continues on our side. We are now experiencing OOM in metaspace using 1.3.5. These environments are Cloud Foundry deployments where the container has much less memory available. I'm assuming we haven't seen it on standard deployments or docker deployments because there is much more memory available. The simple test has been running for 30 mins and shows it close to the limit but seems to have plateaued. My test might have to get more complex. 

Do your tests show issues with metaspace?

**Comment by terryherron** [comment] 2016-09-09 22:05
The classes are constantly increasing in my experiment.  The heap seems to GC fine, but the metaspace increases with the classes.  Maybe CGLIB or something else is holding references to older classes that have been refreshed to new.  So the leaked old classes can't be GCed from metaspace?

I've raise the metaspace to 256m here, but at 104m it dies in 10 minutes.  The 104m is what the Cloud Foundry java build pack memory calculator assigned. 

![image](https://cloud.githubusercontent.com/assets/13223773/18404291/b847fd1e-76b7-11e6-9b7e-ce9e523d3b40.png)

**Comment by terryherron** [comment] 2016-09-10 03:46
My post above was not with the sample app dahmr provided.  It was from my app under development that I can't share.  What I think is happening is the refresh triggers classloading of new proxies and the old proxies are never released for metaspace GC.  So this leaks on every refresh.  Notice the "Loaded" statements.

2016-09-09 18:34:11.285  INFO 11 --- [ask-scheduler-7] o.s.c.e.event.RefreshEventListener       :  [] Refresh keys changed: [jvm.java_option_debug_10]
[Loaded com.x.authorization.service.domain.RuleServiceImpl$$EnhancerBySpringCGLIB$$7d2aa9c7_20 from jar:file:/opt/jars/authorization-service-3.3.43.jar!/]
[Loaded sun.reflect.GeneratedSerializationConstructorAccessor188 from __JVM_DefineClass__]
[Loaded com.x.authorization.service.domain.RuleContainerService$$EnhancerBySpringCGLIB$$fa11b9be_21 from jar:file:/opt/jars/authorization-service-3.3.43.jar!/]
[Loaded sun.reflect.GeneratedSerializationConstructorAccessor189 from __JVM_DefineClass__]
[Loaded com.x.authorization.service.domain.RuleServiceImpl$$EnhancerBySpringCGLIB$$7d2aa9c7_20$$FastClassBySpringCGLIB$$22c3c74f from jar:file:/opt/jars/authorization-service-3.3.43.jar!/]
[Loaded com.x.authorization.service.domain.RuleContainerService$$EnhancerBySpringCGLIB$$fa11b9be_21$$FastClassBySpringCGLIB$$82593ba6 from jar:file:/opt/jars/authorization-service-3.3.43.jar!/]
[Loaded com.x.authorization.service.config.properties.AncestryProperties$$EnhancerBySpringCGLIB$$313495b3_21 from jar:file:/opt/jars/authorization-service-3.3.43.jar!/]
[Loaded sun.reflect.GeneratedSerializationConstructorAccessor190 from __JVM_DefineClass__]
[Loaded com.x.authorization.service.config.properties.AncestryProperties$$EnhancerBySpringCGLIB$$313495b3_21$$FastClassBySpringCGLIB$$8ee49696 from jar:file:/opt/jars/authorization-service-3.3.43.jar!/]
2016-09-09 18:34:47.961  INFO 11 --- [ask-scheduler-5] sDataSourceApplicationContextInitializer :  [] [c.sas.commons.db.support:DATASOURCE_SKIP_NOT_ENABLED] Skipping the setting of DataSource properties; 'x.datasource.initializer.enabled' disabled.
2016-09-09 18:34:48.288  INFO 11 --- [ask-scheduler-5] s.c.a.AnnotationConfigApplicationContext :  [] Refreshing

**Comment by dsyer** [comment] 2016-09-10 06:43
What is `com.x.authorization.service.domain.RuleServiceImpl` doing in there? What is it, and why does it get loaded?

**Comment by terryherron** [comment] 2016-09-11 00:53
The internal app I had been using to replicate the leak has 11 RefreshScope annotated beans.   I just wanted to offer my thoughts on this being a metaspace issue around stale proxies not being released with refreshes.  Thank you all for promptly looking into this issue.  It was not my intention to distract from dahamr's post, just to offer a theory about were I think the leak lives.   Thank you.

![image](https://cloud.githubusercontent.com/assets/13223773/18414473/e3a5026e-7797-11e6-9f5b-b2d1b20e4840.png)

**Comment by terryherron** [comment] 2016-09-11 02:29
Just noticed nissel's comment on Jul 18.  We aren't using Eureka. However his seeing lots of cglib enhanced MethodProxy classes not getting garbage collected was my point.  Thanks.

**Comment by dsyer** [comment] 2016-09-11 11:06
I don't see any direct evidence yet for what proxies are doing and having done to them that causes a leak. They might well be central to the issue, but there's no smoking gun, so we need more. Spencer also found instances of `AnnotationConfigApplicationContext` accumulating, which is annoying and might play into the issue, but is unlikely to use much memory, even if it is technically a leak. I'd also like to rule consul out of the picture (none of what we have talked about is anything to do with spring-cloud-consul).

**Comment by dsyer** [comment] 2016-09-11 20:33
Actually there __is__ something different about spring-cloud-consul. This test prints the number of classes loaded by the main app class loader:

```java
public class CreateApplicationTests {
	
	@Test
	public void contextLoads() {
		System.err.println(count());
		new SpringApplicationBuilder(Empty.class).web(false).run().close();
		System.err.println(count());
		new SpringApplicationBuilder(Empty.class).web(false).run().close();
		System.err.println(count());
		new SpringApplicationBuilder(Empty.class).web(false).run().close();
		System.err.println(count());
		new SpringApplicationBuilder(Empty.class).web(false).run().close();
		System.err.println(count());
	}

	private int count() {
		URLClassLoader classLoader = (URLClassLoader)CreateApplicationTests.class.getClassLoader();
		@SuppressWarnings("unchecked")
		Vector<Class<?>> classes = (Vector<Class<?>>) ReflectionTestUtils.getField(classLoader, "classes");
		return classes.size();
	}
	
	@Configuration
	protected static class Empty {
		
	}

}
```

If you run it in a spring-cloud-consul project the count goes up (by 2) on every iteration. In a vanilla Spring Cloud project (e.g. with just spring-cloud-starter-config and sprint-retry) it doesn't.

**Comment by dsyer** [comment] 2016-09-11 20:35
If you try and list the classes that changed it gets a bit weird, but settles down to this kind of thing:

```
[class org.springframework.cloud.consul.config.ConsulPropertySourceLocator$$EnhancerBySpringCGLIB$$866b2dd6_4, class org.springframework.cloud.consul.config.ConsulPropertySourceLocator$$EnhancerBySpringCGLIB$$866b2dd6_4$$FastClassBySpringCGLIB$$a2f04ee4]
```

(Obviously with different class names on each iteration.)

@philwebb I'm a bit stumped on why this is different than a vanilla Spring Boot or Spring Cloud app.

**Comment by terryherron** [comment] 2016-09-11 21:18
Excellent test Dave.  

Just wanted to mention in our environment the leak is larger than 2 classes per refresh.  We have dozens of apps currently with several spring profiles.   This multiplies the number of consul property sources.  Also, multiplied by numerous @RefreshScope beans.  All these come together to increase the leak size from what I gather.  Our folks are investigating to reduce the number of profiles and limit the number of consul refresh occurences to alleviate production issues until this is ultimately resolved.

**Comment by spencergibb** [comment] 2016-09-11 21:19
@terryherron, can I ask why you are using refresh scope?

**Comment by terryherron** [comment] 2016-09-11 21:31
Our platform keeps some configuration in consul. The @RefreshScope beans are so our apps can update in place without the need for restarts.  When consul properties change, it triggers the app refresh and currently leaks a bit.  We noticed the leak when investigating why our apps were restarting themselves.  

I'm not a platform developer at our company, but I first read about Refresh Scope here:
http://cloud.spring.io/spring-cloud-static/docs/1.0.x/spring-cloud.html#_refresh_scope

**Comment by spencergibb** [comment] 2016-09-11 21:35
The reason I ask, is that if you use `@ConfigurationProperties` instead of @Value, you don't need to use refresh scope.

**Comment by dsyer** [comment] 2016-09-12 06:16
Also `@RefreshScope` beans are not normally declared in the `ApplicationContext` used by the `ContextRefresher`, so if they are showing up in that context something else is wrong, or else this is a misreading of something completely different. I think if you have a problem that manifests as OOM it's way more severe than anything I can reproduce, and we need to get more details (like a sample app).

**Comment by dsyer** [comment] 2016-09-12 06:48
Update (see above). This is **not** specific to Consul. You mentioned a "platform" @terryherron, so I presume you have some libraries that are used in the bootstrap phase and those are magnifying the problem. Can we see the code for those please? Or could you at least run the test above in one of your own apps and get a print out of the proxy classes via the class loader, e.g:

```java
	private int count() {
		URLClassLoader classLoader = (URLClassLoader)CreateApplicationTests.class.getClassLoader();
		@SuppressWarnings("unchecked")
		Vector<Class<?>> classes = (Vector<Class<?>>) ReflectionTestUtils.getField(classLoader, "classes");
		Set<Class<?>> news = new HashSet<>();
		for (Iterator<Class<?>> iterator = classes.iterator(); iterator.hasNext();) {
			Class<?> cls = (Class<?>) iterator.next();
			if (!this.classes.contains(cls)) {
				news.add(cls);
			}
		}
		System.err.println(news);
		this.classes.addAll(classes);
		return classes.size();
	}
```

**Comment by terryherron** [comment] 2016-09-12 12:41
Another developer here passed this along:

"Also, I experimented with removing @RefreshScope from all the beans in the authorization service except the configuration properties & thread pool. I do still get duplicate class proxies but only for those injected into other beans which are not singletons and wrapped in an AOP proxy. For example, RuleController does not generate duplicates but AuthorizationController does. The classes which seem to stay around are the $FastClassBySpringCGLIB instances." 

![image](https://cloud.githubusercontent.com/assets/13223773/18436033/4fe70594-78c4-11e6-861a-c6a753efb2a0.png)

![image](https://cloud.githubusercontent.com/assets/13223773/18435950/dff605dc-78c3-11e6-859a-ee54fda07e5b.png)

![image](https://cloud.githubusercontent.com/assets/13223773/18436003/2d88d2e8-78c4-11e6-97ce-623d2fad4b21.png)

**Comment by zachmarshall** [comment] 2016-09-12 17:23
@dsyer: I work with @dahamr and @terryherron. We would not expect those classes to be in the bootstrap context. We do have one `@Configuration` class that is loaded via `org.springframework.cloud.bootstrap.BootstrapConfiguration`, but it does not create those beans you see above in @terryherron's screenshot.

Though @dahamr's sample app does show a leak, are you interested in a sample app that shows the cglib proxy leak as well?

**Comment by terryherron** [comment] 2016-09-12 18:22
Here is a sample app that was just forwarded to me.

https://github.com/terryherron/metaspace-service

**Comment by dsyer** [comment] 2016-09-12 18:31
I don't see anything radically dissimilar that @dahamr described in his sample. I'll check out this new one, but what do you think is different about it? Is there something here that isn't a cglib proxy leak?

**Comment by terryherron** [comment] 2016-09-12 21:43
Our group wasn't running or familiar with dahamr's app as we were using an internal production app for testing.  My apologies.

**Comment by dahamr** [comment] 2016-09-13 01:01
The new sample app is slightly different from mine in that it has a couple refreshScope beans. HelloConfig is autowired into HelloService. I haven't profiled it but I'm told it reproduces a metaspace leak of proxy classes we are seeing in our apps.

**Comment by iaindjackson** [comment] 2016-09-13 08:05
The new example shows the creation of the extra proxy classes. Each run of the loop in the script will create duplicate proxies for HelloService, HelloConfig and ConsulPropertySourceLocator on Spring Boot 1.3.5.RELEASE. 

On 1.3.7.RELEASE and 1.4.0.RELEASE there is only duplicate proxies created for ConsulPropertySourceLocator alongside the heap memory issues.

**Comment by spencergibb** [comment] 2016-09-13 17:48
All uses of `@RefreshScope` in https://github.com/terryherron/metaspace-service are unneeded.

**Comment by dahamr** [comment] 2016-09-13 17:51
Yeah, we were discussing this earlier so I figured you'd say this. I'll make that change and do a little more profiling on our side to confirm the issues is still there.

**Comment by spencergibb** [comment] 2016-09-13 17:54
It's ok, just clarifying usage. We've seen the metaspace, class issue without multiple `@RefreshScope` beans.

**Comment by dahamr** [comment] 2016-09-13 18:02
Good. @iaindjackson has been digging into the metaspace issue so I've been less involved there. I've been focused on trying to prevent all the unnecessary refreshes to mitigate the leaks right now. ConfigWatch is checking a lot of prefixes that don't exist and still generates events. This seems unnecessary so I'm trying to determine if this is a real issue or something of my own doing.

**Comment by dahamr** [comment] 2016-10-28 18:20
Hey Guys. Any updates on this issue? Thanks.

**Comment by dahamr** [comment] 2016-11-09 18:38
So, I guessing there are no updates. Are there any plans on when this will be evaluated further? My team is making plans to consume new versions of dependencies like spring-boot and spring-cloud. This issue has come up in the discussion.

**Comment by dsyer** [comment] 2016-11-09 19:49
Wasn't it fixed in spring cloud commons (something similar was at any rate)? Maybe you'd better just try the upgrade to Camden.SR2?

**Comment by dahamr** [comment] 2016-11-09 19:55
Are you talking about https://github.com/spring-cloud/spring-cloud-consul/issues/223? This is a good fix because it reduces the impact across services. I do not think it addresses the actual memory leak reported in this issue. I'm not aware of any other fixes.

**Comment by dsyer** [comment] 2016-11-09 20:27
That's not in spring cloud commons, so no, that wasn't it.

**Comment by dahamr** [comment] 2016-11-14 04:26
Took me a bit to get to it but I can still reproduce the same symptoms with SB 1.4.1 and SC Camden.SR2. I used the sample app and visualvm to show that AnnotationConfigApplicationContext are still accumulating. Pushed updates to github.com:dahamr/springCloudConsulTest.git with my sample changes.

**Comment by dsyer** [comment] 2016-11-14 09:31
I ran your app for 20 minutes and nothing bad seems to happen (after upgrading to 1.4.2 and Camden snapshots). Profiling with YourKit showed no drift of memory stats and I could only find one instance of `AnnotationConfigApplicationContext`. Is it working now for you?

The strange thing though is that the change I was thinking was going to fix it was actually in Spring Retry, and it wasn't released until today (so it isn't in Boot 1.4.2). Maybe something in Spring Core changed that fixed it incidentally?

**Comment by dahamr** [comment] 2016-11-14 15:02
Maybe we aren't doing the same thing to reproduce. I ran the app using SB 1.4.2 and it showed accumulating AnnotationConfigApplicationContext objects every time a refresh event is triggered. I'm using a simple curl command in a loop incrementing the test value each time. I installed YourKit as well to see if it shows anything different and it does not.

**Comment by dsyer** [comment] 2016-11-14 15:54
We were not doing the same thing (I expected it to break without doing anything, just because of teh consul heartbeat). When I ping the /refresh endpoint I can see `AnnotationConfigApplicationContext` instance count going up. If you upgrade spring-retry they become garbage collectable though (set spring-retry.version=1.1.5.RELEASE in your pom). So I don't think there is anything to fix here. Agree?

**Comment by dahamr** [comment] 2016-11-14 18:55
1.1.5.RELEASE doesn't appear to be available in maven central. I pulled down the source and have not been able to reproduce in my first set of tests. I'll take it to the larger project and see what happens. This will take a little time because the larger project has not been converted to SB 1.4 yet. If this issue needs to be closed, please link it to the spring-retry fix and I'll worry about updating/opening a new issue as soon as I can.

**Comment by dsyer** [comment] 2016-11-14 19:25
Maven Central sync seems to be a bit slow today. You can find it in repo.spring.io. No problem leaving this issue open, but let us know when you find something.

**Comment by dahamr** [comment] 2017-01-07 02:04
Update: We won't be able to go to SB 1.4 for awhile so we put spring-retry 1.1.5 in place on SB 1.3.8. We have been unable to reproduce. Thanks for the help.

**Comment by null-exception** [comment] 2017-04-14 00:44
@dahamr Facing a similar issue with our application. I would like to know which version of spring boot and consul this issue doesn't occur.

**Comment by dsyer** [comment] 2017-04-14 05:35
@NullException maybe you weren't reading the comments above? The fix was in spring-retry 1.1.5 (which you would get with Spring Boot 1.4 or 1.5).

**Closed by dsyer** 2017-04-14 05:35 UTC

**Comment by null-exception** [comment] 2017-04-14 22:07
@dsyer Thanks Dave, But I was confused with other comment where its mentioned that they were able to reproduce this issue with SB 1.4.2. So I wanted to make sure if I can use that or above 1.4.2.

**Comment by gtrivedi20** [comment] 2017-04-28 15:47
We are facing same issue. memory keep increasing when we are using following dependency.
dependencies {
    // AMT2 Dependencies

    //
    // Other deps

    compile(group: 'org.springframework.boot', name: 'spring-boot-starter', version: '1.5.3.RELEASE') {
        exclude(module: 'commons-logging')
    }
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '1.5.3.RELEASE'
    //compile("org.springframework.boot:spring-boot-starter-jetty:1.5.3.RELEASE")

   /* compile group: 'io.springfox', name: 'springfox-swagger-ui', version:'2.2.2'
    compile group: 'io.springfox', name: 'springfox-swagger2', version:'2.2.2'*/

    //compile 'org.springframework.cloud:spring-cloud-core:1.2.3.RELEASE'
    //compile group: 'org.springframework.cloud', name: 'spring-cloud-spring-service-connector', version: '1.2.3.RELEASE'
    //compile group: 'org.springframework.cloud', name: 'spring-cloud-cloudfoundry-connector', version: '1.2.3.RELEASE'

    compile group: 'org.springframework.boot', name: 'spring-boot-starter-actuator', version: '1.5.3.RELEASE'







}

**Comment by dsyer** [comment] 2017-04-29 06:00
@gtrivedi20 I don't see any reference to spring cloud consul or spring-retry in there and you are using more recent spring Boot versions than we discussed above. I don't think your issue is the same.
