### ISSUE TITLE
Service not getting de-registered from consul on exit

### ISSUE THREAD

**Issue by vtahlani** [spring-cloud/spring-cloud-consul#260] opened 2016-12-09 10:09 UTC
Service should get deregistered automatically from consul once we stop the service.

**Comment by spencergibb** [comment] 2016-12-09 17:34
I regularly see services de-registered. Can you please provide more details. What version are you using? What steps are required to reproduce the problem?

**Comment by vtahlani** [comment] 2016-12-12 08:10
Please find details on versions -

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-consul-config</artifactId>
        <version>1.0.2.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-consul-discovery</artifactId>
        <version>1.0.2.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-consul-all</artifactId>
        <version>1.0.2.RELEASE</version>
      </dependency>

I start consul agent, register services and zuul then stop service. Use catalog API to fetch service details, you will get the service. Also i don't get any message saying de-register service in service log.

**Comment by spencergibb** [comment] 2016-12-12 16:06
can you please try with the latest release 1.1.2?

**Comment by vtahlani** [comment] 2016-12-20 14:08
Tried 1.1.2 but still services are not getting de-registered, am I missing any configuration?

         <dependency>
                <groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-consul-discovery</artifactId>
		<version>1.1.2.RELEASE</version
        </dependency>

Can you please share your pom file detsails?

**Comment by vtahlani** [comment] 2016-12-26 13:05
It worked for me in Unix and service got de-register from consul when I used "Ctrl+C" to bring down the service.

However service doesn't get de-register if I click "Terminate button in Eclipse console", so i achieved the same by following below then service got de-registered from consul.

Added spring cloud actuator dependency , which adds all endpoints health, shutdown etc
Used API - localhost:XYZO/shutdown // here XYZO is placeholder for port on which service is running.
output
o.s.c.consul.discovery.ConsulLifecycle : Deregistering service with consul: greeting

don't see service anymore in consul
localhost:8500/v1/catalog/services

looks like it is not respecting signal in Windows.

**Comment by spencergibb** [comment] 2017-01-09 16:52
@vtahlani ok, then that is not a problem for spring-cloud-consul, can we close this?

**Comment by vtahlani** [comment] 2017-01-11 07:49
Should we not enhance consul to respect Windows signal  similar to Ctrl+C in Unix/Linux?

**Comment by spencergibb** [comment] 2017-01-11 19:32
I don't think it has anything to do with consul, possibly spring-boot or even just the jvm

**Comment by titoc** [comment] 2017-09-15 18:29
@vtahlani Trapping the sigterm is upto the container that you are running your application.  The term signal should be passed to your jvm application from its parent process which has forked it. JVM has hooks for shutdown and the spring boot already listens for it.

**Comment by spencergibb** [comment] 2018-01-18 01:13
Closing this due to inactivity. Please re-open if there's more to discuss.

**Closed by spencergibb** 2018-01-18 01:13 UTC
Labels: waiting for feedback
