### ISSUE TITLE
/refresh fails due to a NullPointerException

### ISSUE THREAD

**Issue by tehjakey** [spring-cloud/spring-cloud-consul#70] opened 2015-08-05 15:33 UTC
When the `ConsulPropertySource.java init()` parses the consul folder information from the ?recurse call it is resulting in a key:value pair equal to "":null. This is true for all folder information. Because of this null value a bug in EnvironmentDecryptApplicationInitializer.java:127 is exposed where a NullPointerException is thrown from calling toString() on a null property.

Here's line 127 in EnvironmentDecryptApplicationInitializer.java: 
```
String value = source.getProperty(key).toString();
```

Here's the full stack trace....
```
java.lang.NullPointerException: null
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:127) ~[spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:116) ~[spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:81) ~[spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.cloud.bootstrap.config.RefreshEndpoint.addConfigFilesToEnvironment(RefreshEndpoint.java:87) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.RefreshEndpoint.refresh(RefreshEndpoint.java:72) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.RefreshEndpoint.invoke(RefreshEndpoint.java:121) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.RefreshEndpoint.invoke(RefreshEndpoint.java:47) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:61) [spring-boot-actuator-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.cloud.endpoint.GenericPostableMvcEndpoint.invoke(GenericPostableMvcEndpoint.java:50) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) [spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) [spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
```

**Comment by spencergibb** [comment] 2015-08-05 16:25
What version of spring-cloud-consul are you using?  I believe this is fixed in 1.0.0.BUILD-SNAPSHOT.

**Comment by tehjakey** [comment] 2015-08-05 17:24
I am using 1.0.0.M1. I can retest with 1.0.0.BUILD-SNAPSHOT and report back.

**Comment by spencergibb** [comment] 2015-08-05 17:27
That would be helpful.

**Comment by spencergibb** [comment] 2015-08-05 17:28
Looks like a duplicate of #42

**Comment by tehjakey** [comment] 2015-08-05 17:59
I'm grabbing the

'org.springframework.cloud:spring-cloud-consul-config:1.0.0.BUILD-SNAPSHOT'
from

maven { url "http://repo.spring.io/libs-snapshot-local" }

but now my consul integration is broken... I don't see any properties
loading from my consul server and when i switch back to the 1.0.0.M1
artifact everything is fine.

On Wed, Aug 5, 2015 at 1:28 PM, Spencer Gibb <notifications@github.com>
wrote:

> Looks like a duplicate of #42
> <https://github.com/spring-cloud/spring-cloud-consul/issues/42>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-consul/issues/70#issuecomment-128084105>
> .
>



-- 
Aaron

**Comment by spencergibb** [comment] 2015-08-05 18:03
Probably a different issue there.  Are you using the [dependency-management-plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin)?

**Comment by tehjakey** [comment] 2015-08-05 18:35
I tried with and without the dependency management plugin and get the same
result. I the ConsulAutoConfiguration bean is not loaded when i use the
snapshot, so i'm trying to figure that out.

On Wed, Aug 5, 2015 at 2:03 PM, Spencer Gibb <notifications@github.com>
wrote:

> Probably a different issue there. Are you using the
> dependency-management-plugin
> <https://github.com/spring-gradle-plugins/dependency-management-plugin>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-consul/issues/70#issuecomment-128093182>
> .
>



-- 
Aaron

**Comment by spencergibb** [comment] 2015-08-05 18:38
If you run with `--debug` it will give an autoconfig report or include `spring-boot-starter-actuator` and hit `/autoconfig`.  Search for `ConsulAutoConfiguration` and it will tell you why it wasn't loaded.

**Comment by spencergibb** [comment] 2015-11-11 00:25
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.

**Closed by spencergibb** 2015-11-11 00:25 UTC
Labels: waiting for feedback
