### ISSUE TITLE
Only one consul node restart ,services not auto register

### ISSUE THREAD

**Issue by lcb1208** [spring-cloud/spring-cloud-consul#429] opened 2018-06-07 09:50 UTC
Only one consul node ,If it down ,register services not down ,how ensure services auto register when consul node restart

**Comment by kevin-tan** [comment] 2018-08-03 11:26
This issue is most likely related to this: https://github.com/spring-cloud/spring-cloud-consul/issues/419

**Comment by rotilho** [comment] 2018-12-13 17:41
@lcb1208 did you manage to accomplish that?

I have similar issue

**Comment by spencergibb** [comment] 2018-12-13 17:54
Duplicate of #197

**Closed by spencergibb** 2018-12-13 17:54 UTC
Labels: waiting-for-triage
