### ISSUE TITLE
how to configure cluster for consul in yml

### ISSUE THREAD

**Issue by Alzerzyl** [spring-cloud/spring-cloud-consul#341] opened 2017-08-06 12:09 UTC
In my yml,I config like this

spring:
  cloud:
    consul:
      host: 172.17.99.126
      port: 8500

but now I want make my program to know the cluster of consul.
I have 172.17.99.126,172.17.99.127,172.17.99.131
how can I config yml for consul cluster 

like eureka

eureka:
    client:
        service-url:
            defaultZone: http://jp:jp123456@peer1:8761/eureka/,http://jp:jp123456@peer2:8762/eureka/,http://jp:jp123456@peer3:8763/eureka/

**Comment by aatarasoff** [comment] 2017-08-07 09:00
I think that you don't need this. You could define **_agent_** host and port in your .yml file. In that case, only one endpoint is required cause each server has its own agent.

**Comment by spencergibb** [comment] 2017-08-10 18:04
Duplicate of #307. Eureka and consul have very different architectures. @aatarasoff's comment is spot on.

**Closed by spencergibb** 2017-08-10 18:04 UTC
