### ISSUE TITLE
Spring-cloud-consul-starter-sample Parameter 1 of method binderAwareRouterBeanPostProcessor in org.springframework.cloud.stream.config.BindingServiceConfiguration required a single bean, but 2 were found:

### ISSUE THREAD

**Issue by lalitakhare** [spring-cloud/spring-cloud-consul#554] opened 2019-04-21 11:03 UTC
```
2019-04-21 16:21:54.457  WARN 1113 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'binderAwareRouterBeanPostProcessor' defined in class path resource [org/springframework/cloud/stream/config/BindingServiceConfiguration.class]: Unsatisfied dependency expressed through method 'binderAwareRouterBeanPostProcessor' parameter 1; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.messaging.core.DestinationResolver<org.springframework.messaging.MessageChannel>' available: expected single matching bean but found 2: binderAwareChannelResolver,integrationChannelResolver
2019-04-21 16:21:54.460  INFO 1113 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2019-04-21 16:21:54.476  INFO 1113 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-04-21 16:21:54.479 ERROR 1113 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method binderAwareRouterBeanPostProcessor in org.springframework.cloud.stream.config.BindingServiceConfiguration required a single bean, but 2 were found:
	- binderAwareChannelResolver: defined by method 'binderAwareChannelResolver' in class path resource [org/springframework/cloud/stream/config/BindingServiceConfiguration.class]
	- integrationChannelResolver: defined in null


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

**Comment by lalitakhare** [comment] 2019-04-21 11:08
I have connected to consul agent running on AWS EC2 docker image. Able to access consul from my machine with EC2 IP:8500. Connecting to this agent while making change to bootstrap.yml of spring-cloud-consul-starter-sample.

**Comment by ryanjbaxter** [comment] 2019-05-06 14:35
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by ryanjbaxter** [comment] 2019-05-06 14:35
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by ryanjbaxter** [comment] 2019-05-06 14:37
Were you using SNAPSHOT builds?

**Comment by TYsewyn** [comment] 2019-07-24 18:06
Could you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) so we can reproduce this issue?
I ran the sample in the repository with the Spring Cloud Stream RabbitMQ binder in following setups without any problem:
- Spring Boot 2.0.8.RELEASE + Spring Cloud Finchley.SR4
- Spring Boot 2.1.6.RELEASE + Spring Cloud Greenwich.SR2
- Spring Boot 2.2.0.BUILD-SNAPSHOT + Spring Cloud Hoxton.BUILD-SNAPSHOT

**Comment by spring-issuemaster** [comment] 2019-07-31 18:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-08-07 18:09
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-08-07 18:09 UTC
Labels: feedback-reminder, waiting for feedback
