### ISSUE TITLE
Consul with turbine in Spring Cloud Dalston

### ISSUE THREAD

**Issue by AmramXing** [spring-cloud/spring-cloud-consul#406] opened 2018-03-14 01:58 UTC
I am using consul with turbine in spring cloud dalston.sr1 version, it had two service, turbine service run on port 15010, aservice run on port 15011.(follow sample _https://github.com/spencergibb/consul-turbine-example_)
Turbine **application.properties**
.........
**spring.application.name=myturbine
server.port=15010
spring.profiles.active=development
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
turbine.appConfig=aservice
turbine.aggregator.clusterConfig=aservice**
........

When I visit http://localhost:15011/hystrix.stream, It show 'ping ...', I use hystrix dashboard to monitor _http://localhost:15011/hystrix.stream_, it is good.
Where I input _http://localhost:15010/turbine.stream_, it report 404 not found. When I use hystrix dashboard to monitor _'http://localhost:15010/turbine.stream'_, it report "Unable to connect to Command Metric Stream."
Turbine service's log show.
**2018-03-12 17:54:44.556 INFO 21008 --- [io-15010-exec-9] c.n.t.s.servlet.TurbineStreamServlet : FilterCriteria: []
2018-03-12 17:54:44.556 INFO 21008 --- [io-15010-exec-6] c.n.t.s.servlet.TurbineStreamServlet : FilterCriteria: []
2018-03-12 17:54:44.556 INFO 21008 --- [io-15010-exec-9] c.n.t.s.servlet.TurbineStreamServlet : StatsType filters: []
2018-03-12 17:54:44.556 INFO 21008 --- [io-15010-exec-6] c.n.t.s.servlet.TurbineStreamServlet : StatsType filters: []
2018-03-12 17:54:44.564 WARN 21008 --- [io-15010-exec-4] ashboardConfiguration$ProxyStreamServlet : Failed opening connection to http://localhost:15010/turbine.stream : 404 : HTTP/1.1 404
2018-03-12 17:54:44.567 WARN 21008 --- [io-15010-exec-3] ashboardConfiguration$ProxyStreamServlet : Failed opening connection to http://localhost:15010/turbine.stream : 404 : HTTP/1.1 404**

**Note:** 
If I use **turbine.aggregator.clusterConfig=aservice** , _/turbine.stream_ or _/turbine.stream?cluster=aservice_, reported 404 not found error.
If I not used **turbine.aggregator.clusterConfig**, _/turbine.stream_ show correct. But hystrix dashboard did not show any data in it's UI, only show 'Loading ...'

**Comment by AmramXing** [comment] 2018-03-22 09:10
@spencergibb

**Comment by spencergibb** [comment] 2018-04-02 15:43
@AmramXing 
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2018-10-02 17:00
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Closed by spring-issuemaster** 2018-10-02 17:00 UTC
Labels: feedback-provided, question

**Comment by spencergibb** [comment] 2019-02-05 19:01
@sigalmaya Dalston is no longer supported. Please try with Edgware, Finchley or Greenwich.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
