### ISSUE TITLE
properties in application.yml are not loaded

### ISSUE THREAD

**Issue by derylseale** [spring-cloud/spring-cloud-consul#43] opened 2015-06-18 00:45 UTC
I have been unable to get spring-cloud-consul to recognize any consul related properties in my application.yml file. I started with the following:

```
spring:
  cloud:
    consul:
      config:
        enabled: false
```
This is to disable consul configuration in my CI profile. This doesn't seem to work, as the application tries and fails to load KV data from a running consul instance. I've experimented with other properties (e.g. `spring.cloud.consul.port`), but no matter what I specify, the values are not being used by spring-cloud-consul. 

I've also tried specifying properties in a bootstrap.yml file, but without any success.

Is this a bug, or am I configuring spring-cloud-consul in the wrong place?

**Comment by spencergibb** [comment] 2015-06-18 20:44
I did have to put `spring.cloud.consul.port` in `bootstrap.yml` because s-c-consul-config uses the bootstrap context.  `spring.cloud.consul.config.enabled=false` didn't work (in bootstrap).  That issue has been fixed in 90dfce599035cfacb63469d0088c52a333b47d96.  Otherwise, I'm unable to reproduce your issue.  Do you have a project you can share that duplicates the problem?

**Comment by derylseale** [comment] 2015-06-18 20:53
I think you can reproduce the issue just using the sample application provided in spring-cloud-consul-sample. If you add `spring.cloud.consul.config.enabled: false` to the application.yml file, rebuild and package per the instructions, and re-launch the JAR file, you'll see that it still tries to connect to a running consul agent.

**Comment by spencergibb** [comment] 2015-06-18 20:59
I was using the sample app.  `spring.cloud.consul.config.enabled=false` __does work__ in `bootstrap.yml` (not `application.yml`) after my fix.  Other properties are also working.

**Comment by derylseale** [comment] 2015-06-18 23:56
So do all the consul related properties have to be specified in bootstrap.yml? The [documentation](spring-cloud-consul-sample/src/main/resources/application.yml) only mentions application.yml.

**Closed** 2015-06-19 01:29 UTC

**Comment by spencergibb** [comment] 2015-06-19 01:31
If you use Consul Config, the values under `spring.cloud.consul.config.*` and the connection information `spring.cloud.consul.{host|port}` do.  The docs have been updated to reflect that here 2a019eccc3915208dcd3045b9eedcf45895dd1fa.
