### ISSUE TITLE
Custom health check in Spring Boot

### ISSUE THREAD

**Issue by udoless** [spring-cloud/spring-cloud-consul#335] opened 2017-07-14 11:09 UTC
I am using consul in my spring boot project. And project's health check endpoint requires a `basic auth`. So how to config Spring to implement this? Or Can I use `script` health check in Spring?

Thanks for your reply!

**Comment by spencergibb** [comment] 2017-07-18 22:35
Can you elaborate on what your problem is? I'm still unsure what the problem is?

**Comment by spencergibb** [comment] 2018-01-18 01:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 01:10 UTC
Labels: question, waiting for feedback
